apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dask-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://helm.dask.org
    chart: dask-kubernetes-operator
    targetRevision: 2024.9.0
    helm:
      valuesObject:
  destination:
    namespace: dask-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true